export const FIND_ALL_WIDGETS = 'FIND_ALL_WIDGETS';
export const DELETE_WIDGET = 'DELETE_WIDGET';
export const ADD_WIDGET = 'ADD_WIDGET';
export const SAVE = 'SAVE';
export const SELECT_WIDGET_TYPE = 'SELECT_WIDGET_TYPE';
export const HEADING_SIZE_CHANGED = 'HEADING_SIZE_CHANGED';
export const HEADING_TEXT_CHANGED = 'HEADING_TEXT_CHANGED';
export const WIDGET_NAME_CHANGED = 'WIDGET_NAME_CHANGED';
export const PREVIEW = 'PREVIEW';
export const MOVE_UP = 'MOVE_UP';
export const MOVE_DOWN = 'MOVE_DOWN';

export const PARA_TEXT_CHANGED = 'PARA_TEXT_CHANGED';
export const WIDGET_PARA_NAME_CHANGED = 'WIDGET_PARA_NAME_CHANGED';

export const LIST_ORDER_CHANGED = 'LIST_ORDER_CHANGED';
export const LIST_NAME_CHANGED = 'LIST_NAME_CHANGED';
export const LIST_TEXT_CHANGED = 'LIST_TEXT_CHANGED';

export const SEARCH_NAME_CHANGED = 'SEARCH_NAME_CHANGED';
export const WIDGET_IMAGE_SRC_CHANGED = 'WIDGET_IMAGE_SRC_CHANGED';
export const WIDGET_NAME_IMAGE_CHANGED = 'WIDGET_NAME_IMAGE_CHANGED';
export const SEARCH_NAME_RENDER = 'SEARCH_NAME_RENDER';
export const ASSIGN_URL = 'ASSIGN_URL';
